{application,msisdndb,
             [{description,"MSISDN numbering plan"},
              {vsn,"1.0"},
              {modules,[ets_interval_db,msisdndb,msisdndb_app,
                        msisdndb_cfg_util,msisdndb_extra,msisdndb_extra_imp,
                        msisdndb_gen_sync,msisdndb_gendb_interval,
                        msisdndb_imp_utils,msisdndb_loader,
                        msisdndb_loader_cbextra,msisdndb_loader_cbfix,
                        msisdndb_loader_cbmob,msisdndb_loader_cbrdc,
                        msisdndb_npfix,msisdndb_npfix_imp,msisdndb_npmob,
                        msisdndb_npmob_imp,msisdndb_rdc,msisdndb_rdc_imp,
                        msisdndb_stats,msisdndb_sup,msisdndb_tab_loader,
                        msisdndb_tab_loader_sup,msisdndb_tab_sync]},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{msisdndb_app,[]}},
              {env,[]}]}.
